#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# - Listens on port 80.
# - Returns a page containing "Hello World!" when queried
#   at the root with a curl GET request.

# Update the package repository
apt-get update

# Install Nginx
apt-get -y install nginx

# Create directory html
mkdir /etc/nginx/html

# Create a simple HTML file with "Hello World!" content
echo "Hello World!" > /etc/nginx/html/index.html

# Create the Nginx server block configuration
printf %s "server {
     listen    80 default_server;
     listen    [::]:80 default_server;
     root      /etc/nginx/html;
     index     index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Restart Nginx (without using systemctl)
sudo service nginx restart

# Ensure Nginx is listening on port 80
lsof -i :80

# Check if Nginx is running and accessible
if [ "$(curl -s -o /dev/null -w '%{http_code}' http://localhost)" == "200" ]; then
  echo "Nginx installed and configured successfully!"
else
  echo "Nginx installation and configuration failed!"
fi
