#!/usr/bin/env bash

# Check if an argument is passed
if [ $# -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Perform the ping 5 times and display the result
ping -c 5 "$1"
