#!/usr/bin/env bash
# Script to display "To infinity and beyond" indefinitely
# and react to SIGTERM signal with "I am invincible!!!"

trap "echo 'I am invincible!!!'" SIGTERM
x=0
until [ $x -gt 1 ]
do
	echo "To infinity and beyond"
        sleep 2
done
