#!/usr/bin/env bash

# Script: display_passwd.sh
# Description: Displays the content of the file /etc/passwd with only the required information: username, user id, and home directory path for each user.
# Usage: ./display_passwd.sh

while IFS=':' read -r username _ uid _ home _
do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
