#!/usr/bin/env bash

# Script: parse_apache_logs.sh
# Description: Displays the visitor IP along with the HTTP status code from the Apache log file.
# Usage: ./parse_apache_logs.sh

file="./apache-access.log"
awk '{print $1, $9}' apache-access.log
