#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

# Stop the current Nginx service
service nginx stop

# Update the user in the Nginx config file to be nginx
sed -i 's/user .*;/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx to listen on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart

# Verify that Nginx is running as nginx user
ps aux | grep 'nginx: master' | grep -v grep

# Verify that Nginx is listening on port 8080
netstat -plntu | grep '8080'
