#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080
nginx -s stop
sed -i 's/user .*;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen .*;/listen 8080;/' /etc/nginx/sites-available/default
nginx
